set(TARGET llama-affinity-wave-bench)
add_executable(${TARGET} affinity-wave-bench.cpp)
target_include_directories(${TARGET} PRIVATE ${CMAKE_CURRENT_SOURCE_DIR}/../../ggml/src/ggml-cuda)
target_link_libraries(${TARGET} PRIVATE ggml-cuda ggml ${CMAKE_THREAD_LIBS_INIT})
target_compile_features(${TARGET} PRIVATE cxx_std_17)
